apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-ingestion
  namespace: decigenie
  labels:
    app: document-ingestion
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-ingestion
  template:
    metadata:
      labels:
        app: document-ingestion
        component: backend
    spec:
      containers:
      - name: document-ingestion
        image: gcr.io/decigenie-llm/decigenie-document-ingestion:latest
        ports:
        - containerPort: 8001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: decigenie-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: decigenie-config
              key: DOCUMENT_INGESTION_PORT
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: decigenie-config
              key: UPLOAD_DIR
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: decigenie-secrets
              key: DATABASE_URL
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: document-ingestion
  namespace: decigenie
  labels:
    app: document-ingestion
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: document-ingestion
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: decigenie
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
 