apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-query-service
  namespace: decigenie
  labels:
    app: llm-query-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-query-service
  template:
    metadata:
      labels:
        app: llm-query-service
        component: backend
    spec:
      containers:
      - name: llm-query-service
        image: gcr.io/decigenie-llm/decigenie-llm-query-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: decigenie-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: decigenie-config
              key: LLM_QUERY_SERVICE_PORT
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: decigenie-secrets
              key: GEMINI_API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: decigenie-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llm-query-service
  namespace: decigenie
  labels:
    app: llm-query-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: llm-query-service 