apiVersion: v1
kind: Secret
metadata:
  name: decigenie-secrets
  namespace: decigenie
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  GEMINI_API_KEY: <base64-encoded-gemini-api-key>
  DATABASE_URL: <base64-encoded-database-url>
  POSTGRES_PASSWORD: <base64-encoded-db-password> 