name: Minimal Structure Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  structure-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Check Repository Structure
      run: |
        echo "=== Repository Structure Check ==="
        echo "Working directory: $(pwd)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo ""
        echo "Root directory contents:"
        ls -la
        echo ""
        
        # Check each service directory
        for service in frontend llm-query-service document-ingestion; do
          echo "=== Checking $service ==="
          if [ -d "$service" ]; then
            echo "✓ $service directory exists"
            echo "Contents:"
            ls -la "$service"
            echo ""
            
            if [ -f "$service/package.json" ]; then
              echo "✓ package.json exists"
              echo "Package info:"
              node -p "const pkg = require('./$service/package.json'); console.log('Name:', pkg.name); console.log('Version:', pkg.version); console.log('Test script:', pkg.scripts?.test || 'Not found')"
            else
              echo "✗ package.json missing"
            fi
          else
            echo "✗ $service directory missing"
          fi
          echo ""
        done

    - name: Test Basic Installation
      run: |
        echo "=== Testing Basic Installation ==="
        
        # Test frontend
        echo "Testing frontend installation..."
        cd frontend
        npm install --silent
        echo "✓ Frontend dependencies installed"
        
        # Test LLM service
        echo "Testing LLM service installation..."
        cd ../llm-query-service
        npm install --silent
        echo "✓ LLM service dependencies installed"
        
        # Test document ingestion
        echo "Testing document ingestion installation..."
        cd ../document-ingestion
        npm install --silent
        echo "✓ Document ingestion dependencies installed"
        
        echo "All installations successful!"

    - name: Test Basic Commands
      run: |
        echo "=== Testing Basic Commands ==="
        
        # Test frontend build
        echo "Testing frontend build..."
        cd frontend
        npm run build
        echo "✓ Frontend build successful"
        
        # Test backend services can start (dry run)
        echo "Testing backend services..."
        cd ../llm-query-service
        node -e "console.log('LLM service can be imported')"
        echo "✓ LLM service import successful"
        
        cd ../document-ingestion
        node -e "console.log('Document ingestion service can be imported')"
        echo "✓ Document ingestion service import successful"
        
        echo "All basic commands successful!" 